QLSV_BlockChain/Areas/Admin/Controllers/NguoiDungsController.cs
using QLSV_BlockChain.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace QLSV_BlockChain.Areas.Admin.Controllers
{
    public class NguoiDungsController : Controller
    {
        private BlockChain_QLSVDataContext db = new BlockChain_QLSVDataContext();
        // GET: Admin/NguoiDungs
        public ActionResult Index()
        {
            var nguoiDungs = db.NguoiDungs.ToList();
            return View(nguoiDungs);
        }

        public string mahoa(String str)
        {
            MD5 encrypt = MD5.Create();
            byte[] inputBytes = System.Text.Encoding.ASCII.GetBytes(str);
            byte[] hash = encrypt.ComputeHash(inputBytes);
            StringBuilder sb = new StringBuilder();
            for(int i = 0; i < hash.Length; i++)
            {
                sb.Append(hash[i]);
            }
            return sb.ToString();
        }

        public ActionResult Create()
        {
            ViewBag.MaVaiTro = new SelectList(db.VaiTros, "MaVaitro", "TenVaiTro");
            return View();
        }

        // POST: Admin/NguoiDungs/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TaiKhoan,MatKhau,Mota,MaVaiTro,SoE,SoN")] NguoiDung nguoiDung)
        {
            var isUnique = db.NguoiDungs.FirstOrDefault(p => p.TaiKhoan.Equals(nguoiDung.TaiKhoan));
            if(isUnique != null)
            {
                ViewBag.Error = "Tên tài khoản này đã tồn tại ! Vui lòng chọn tên tài khoản khác.";
                ViewBag.MaVaiTro = new SelectList(db.VaiTros, "MaVaitro", "TenVaiTro", nguoiDung.MaVaiTro);
                return View(nguoiDung);
            }
            if(nguoiDung.MatKhau == null)
            {
                ViewBag.Error = "Mật khẩu không được để trống !";
                ViewBag.MaVaiTro = new SelectList(db.VaiTros, "MaVaitro", "TenVaiTro", nguoiDung.MaVaiTro);
                return View(nguoiDung);
            }
            nguoiDung.MatKhau = mahoa(nguoiDung.MatKhau);
            nguoiDung.IsActive = 0;
            if (ModelState.IsValid)
            {
                db.NguoiDungs.InsertOnSubmit(nguoiDung);
                db.SubmitChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaVaiTro = new SelectList(db.VaiTros, "MaVaitro", "TenVaiTro", nguoiDung.MaVaiTro);
            return View(nguoiDung);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            NguoiDung nguoiDung = db.NguoiDungs.FirstOrDefault(n => n.MaNguoiDung.Equals(id));
            nguoiDung.MatKhau = null;
            if (nguoiDung == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaVaiTro = new SelectList(db.VaiTros, "MaVaitro", "TenVaiTro", nguoiDung.MaVaiTro);
            return View(nguoiDung);
        }

        // POST: Admin/NguoiDungs/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaNguoiDung,TaiKhoan,MatKhau,MoTa,MaVaiTro,SoE,SoN")] NguoiDung nguoiDung)
        {
            if (ModelState.IsValid)
            {
                var user = db.NguoiDungs.FirstOrDefault(n => n.MaNguoiDung.Equals(nguoiDung.MaNguoiDung));
                user.TaiKhoan = nguoiDung.TaiKhoan;
                if(nguoiDung.MatKhau != null)
                {
                    user.MatKhau = mahoa(nguoiDung.MatKhau);
                }
                user.Mota = nguoiDung.Mota;
                user.MaVaiTro = nguoiDung.MaVaiTro;
                db.SubmitChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaVaiTro = new SelectList(db.VaiTros, "MaVaitro", "TenVaiTro", nguoiDung.MaVaiTro);
            return View(nguoiDung);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NguoiDung nguoiDung = db.NguoiDungs.FirstOrDefault(p => p.MaNguoiDung.Equals(id));
            if (nguoiDung == null)
            {
                return HttpNotFound();
            }
            return View(nguoiDung);
        }

        // POST: Admin/NguoiDungs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NguoiDung nguoiDung = db.NguoiDungs.FirstOrDefault(p => p.MaNguoiDung.Equals(id));
            nguoiDung.IsActive = 0;
            db.SubmitChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Active(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NguoiDung nguoiDung = db.NguoiDungs.FirstOrDefault(p => p.MaNguoiDung.Equals(id));
            if (nguoiDung == null)
            {
                return HttpNotFound();
            }
            return View(nguoiDung);
        }

        [HttpPost, ActionName("Active")]
        [ValidateAntiForgeryToken]
        public ActionResult ActiveConfirmed(int id)
        {
            NguoiDung nguoiDung = db.NguoiDungs.FirstOrDefault(p => p.MaNguoiDung.Equals(id));
            nguoiDung.IsActive = 1;
            db.SubmitChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLSV_BlockChain/Areas/Admin/Views/NguoiDungs/Active.cshtml
@model QLSV_BlockChain.Models.NguoiDung

@{
    ViewBag.Title = "Active";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


<h2>Kích hoạt người dùng</h2>

<h3>Có chắc chắn kích hoạt người dùng này?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.Label("Vai trò")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VaiTro.TenVaiTro)
        </dd>

        <dt>
            @Html.Label("Tên tài khoản")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaiKhoan)
        </dd>
        <dt>
            @Html.Label("Mô tả")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mota)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xác nhận" class="btn btn-danger" />
        </div>
    }
</div>

QLSV_BlockChain/Areas/Admin/Views/NguoiDungs/Create.cshtml
@model QLSV_BlockChain.Models.NguoiDung

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Thêm mới người dùng</h2>

@using (Html.BeginForm("Create","NguoiDungs",FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Tên đăng nhập", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TaiKhoan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TaiKhoan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Mật khẩu", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Mô tả", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mota, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mota, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaVaiTro, "Quyền", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaVaiTro", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaVaiTro, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm mới người dùng" class="btn btn-primary" />
            </div>
        </div>
        <div>@ViewBag.Error</div>
    </div>
}

QLSV_BlockChain/Areas/Admin/Views/NguoiDungs/Delete.cshtml
@model QLSV_BlockChain.Models.NguoiDung
@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Vô hiệu hóa người dùng</h2>

<h3>Có chắc chắn vô hiệu hóa người dùng này? Sau khi vô hiệu hóa người dùng sẽ không thể đăng nhập</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.Label("Vai trò")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VaiTro.TenVaiTro)
        </dd>

        <dt>
            @Html.Label("Tên tài khoản")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaiKhoan)
        </dd>
        <dt>
            @Html.Label("Mô tả")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mota)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xác nhận" class="btn btn-danger" />
        </div>
    }
</div>

QLSV_BlockChain/Areas/Admin/Views/NguoiDungs/Edit.cshtml
@model QLSV_BlockChain.Models.NguoiDung

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<br />
<h2>Chỉnh sửa người dùng</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaNguoiDung)

        <div class="form-group">
            @Html.LabelFor(model => model.TaiKhoan,"Tên đăng nhập", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TaiKhoan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TaiKhoan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MatKhau,"Mật khẩu", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mota,"Mô tả", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mota, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mota, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaVaiTro, "Quyền", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaVaiTro", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaVaiTro, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.SoE, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SoE, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SoE, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SoN, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SoN, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SoN, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Chỉnh sửa" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

@*<div>
        @Html.ActionLink("Back to List", "Index")
    </div>*@

QLSV_BlockChain/Areas/Admin/Views/NguoiDungs/Index.cshtml
@model IEnumerable<QLSV_BlockChain.Models.NguoiDung>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<br />

<h2>Quản lý người dùng</h2>

<p>
    <button class="btn-info"> @Html.ActionLink("Thêm mới", "Create", new { }, new { @style = "color:white;" }) </button>
</p>
<table class="table table-bordered table-hover">
    <tr>
        <th>
            @Html.Label("Tài khoản")
        </th>

        <th>
            @Html.Label("Mô tả")
        </th>

        <th>
            @Html.Label("Vai trò")
        </th>

        <th>
            @Html.Label("Trạng thái")
        </th>

        <th>
            @Html.Label("Tác vụ")

        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TaiKhoan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mota)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VaiTro.TenVaiTro)
            </td>
            <td>
                @{ 
                    if(item.IsActive == 0)
                    {
                    <div style="color:red">Vô hiệu hóa</div>
                    }
                    else if(item.IsActive == 1)
                    {
                    <div style="color:slateblue">Hoạt động</div>
                    }
                }
            </td>
            <td>
                <button class="btn btn-warning">
                    @Html.ActionLink("Sửa", "Edit", new { id = item.MaNguoiDung }, new { @style = "color:white;" })
                </button>
                @{
                    if (item.IsActive == 1)
                    {
                        <button class="btn btn-danger">
                            @Html.ActionLink("Vô hiệu hóa", "Delete", new { id = item.MaNguoiDung }, new { @style = "color:white;" })
                        </button>
                    }
                    else if (item.IsActive == 0)
                    {
                        <button class="btn btn-success">
                            @Html.ActionLink("Kích hoạt", "Active", new { id = item.MaNguoiDung }, new { @style = "color:white;" })
                        </button>
                    }
                }
            </td>
        </tr>
    }

</table>