QLSV_BlockChain/Controllers/SVController.cs
using QLSV_BlockChain.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace QLSV_BlockChain.Controllers
{
    public class SVController : Controller
    {
        private BlockChain_QLSVDataContext db = new BlockChain_QLSVDataContext();
        // GET: SinhVien
        public ActionResult Index()
        {
            var sinhvien = db.SinhViens.ToList();
            return View(sinhvien);
        }
        public string mahoa(String str)
        {
            MD5 encrypt = MD5.Create();
            byte[] inputBytes = System.Text.Encoding.ASCII.GetBytes(str);
            byte[] hash = encrypt.ComputeHash(inputBytes);
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < hash.Length; i++)
            {
                sb.Append(hash[i]);
            }
            return sb.ToString();
        }

        public ActionResult Dangxuat()
        {
            Session["userAdmin"] = null;
            return Redirect("~/Admin/HomeAdmin/DangNhap");
        }

        public ActionResult BangDiem()
        {
            var bangDiem = db.BangDiems.ToList();
            return View(bangDiem);
        }
        public ActionResult EditTaiKhoan(int id)
        {
            var edit = db.SinhViens.FirstOrDefault(p => p.IDSinhVien == id);
            edit.matkhau = null;
            return View(edit);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditTaiKhoan([Bind(Include = "IDSinhVien,TenSinhVien,Lop,KhoaVien,NgaySinh,TrangThai,taikhoan,matkhau")] SinhVien sinhVien)
        {
            if (ModelState.IsValid)
            {
                var user = db.SinhViens.FirstOrDefault(n => n.IDSinhVien.Equals(sinhVien.IDSinhVien));
                user.taikhoan = sinhVien.taikhoan;
                user.matkhau = mahoa(sinhVien.matkhau);
                db.SubmitChanges();
                return RedirectToAction("Index");
            }
            return View(sinhVien);
        }
    }
}

QLSV_BlockChain/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

QLSV_BlockChain/Views/Shared/_LayoutSinhVien.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Dashboard - SB Admin</title>
    <link href="~/Content/layoutAdmin/css/styles.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" crossorigin="anonymous"></script>
</head>
@{
    var userAdmin = Session["userAdmin"] as QLSV_BlockChain.Models.SinhVien;

}
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark badge-success">
        <a class="navbar-brand" href="@Url.Action("Index", "HomeAdmin")"><img src="~/Content/images/logo.png" width="210" height="50" /></a>
        <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#">
            <i class="fas fa-bars"></i>
        </button><!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Từ khóa..." aria-label="Search" aria-describedby="basic-addon2" />
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
                </div>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="#">Cài đặt</a><a class="dropdown-item" href="#">Nhật kí</a>
                    <div class="dropdown-divider"></div>
                    <a class=" dropdown-item" href="@Url.Action("Dangxuat", "SV")"> Đăng xuất</a>

                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        @{
                            if (userAdmin != null)
                            {
                                <div class="sb-sidenav-menu-heading" style="color:red">Xin chào: @userAdmin.TenSinhVien </div>

                            }
                        }
                        <div class="sb-sidenav-menu-heading"> <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>Quản lý chức năng</div>
                        @{
                            if (true)
                            {
                                <a class="nav-link" href="@Url.Action("Index", "SV")"> <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>Thông tin sinh viên</a>
                                <a class="nav-link" href="@Url.Action("BangDiem", "SV")"> <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div> Xem điểm</a>
                                <a class="nav-link" href="@Url.Action("EditTaiKhoan", "SV", new {id = userAdmin.IDSinhVien})"> <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>Đổi mật khẩu</a>
                            }
                        }

                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                    Authentication
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav"><a class="nav-link" href="login.html">Login</a><a class="nav-link" href="register.html">Register</a><a class="nav-link" href="password.html">Forgot Password</a></nav>
                                </div>
                                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                    Error
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav"><a class="nav-link" href="401.html">401 Page</a><a class="nav-link" href="404.html">404 Page</a><a class="nav-link" href="500.html">500 Page</a></nav>
                                </div>
                            </nav>
                        </div>

                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Đồ án chuyên ngành</div>
                    Nhóm 10
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted"> CNTT - HUTECH &copy; 2020</div>
                        <div>
                            <a href="#"> Xem thêm</a>
                            &middot;
                            <a href="#">BlockChain &amp; ATTT</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/Content/layoutAdmin/js/scripts.js"></script>
</body>
</html>