QLSV_BlockChain/Areas/KiemDinh/Controllers/ChuKyRSAController.cs
using QLSV_BlockChain.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Security.Cryptography;
using System.Numerics;

namespace QLSV_BlockChain.Areas.KiemDinh.Controllers
{
    public class ChuKyRSAController : Controller
    {
        private BlockChain_QLSVDataContext db = new BlockChain_QLSVDataContext();
        // GET: KiemDinh/ChuKyRSA
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken] 
        public ActionResult Index(FormCollection Thongtin)
        {
            // Lấy ra Mã cơ quan kiểm định từ View
            string MaND = Thongtin["MaNguoiDung"].ToString();
            // Gọi đến hàm khởi tạo và sinh khóa RSA tự động
            KhoiTao();
            TaoMoiKhoa();
            // Tìm ra cơ quan kiểm định đang tạo khóa trong CSDL
            NguoiDung nguoidung = db.NguoiDungs.FirstOrDefault(p => p.MaNguoiDung.Equals(int.Parse(MaND)));
            // Lưu lại khóa công khai của CQ Kiểm định vào CSDL
            nguoidung.SoE = "" + e;
            nguoidung.SoN = "" + N;
            db.SubmitChanges();
            if (d != 0)
            {
                // Hiển thị khóa bí mật của CQ Kiểm định
                ViewBag.thongbao = "Khóa bí mật của bạn là :";
                ViewBag.d = "" + d;
                ViewBag.canthan = "Lưu ý không nên để lộ khóa bí mật cho bất kì ai";
            }
            else
            {
                ViewBag.loi = " Tạo khóa lỗi";
            }
            return View();
        }
        class RandomBigInteger : Random
        {
            public RandomBigInteger() : base()
            {
            }

            public RandomBigInteger(int Seed) : base(Seed)
            {
            }

            public BigInteger NextBigInteger(int bitLength)
            {
                if (bitLength < 1) return BigInteger.Zero;
                int bytes = bitLength / 8;
                int bits = bitLength % 8;
                byte[] bs = new byte[bytes + 1];
                NextBytes(bs);
                byte mask = (byte)(0xFF >> (8 - bits));
                bs[bs.Length - 1] &= mask;
                return new BigInteger(bs);
            }
        }
        BigInteger PK = 0, SK = 0, Modulo = 0;

        BigInteger p = 0, q = 0, N = 0, n = 0, e = 0, d = 0, mid_e = 0;
        int length = 256;
        RandomBigInteger random_big = new RandomBigInteger();
        Random random = new Random();
        // GET: Admin/TaoMoiRSA
        void KhoiTao()
        {
            do
                p = random_odd(length);
            while (is_prime(p) == false);
            while (true)
            {
                q = random_odd(length);
                if (is_prime(q) && p != q) break;
            }
            N = p * q;
            n = (p - 1) * (q - 1);
        }
        void TaoMoiKhoa()
        {
            while (true)
            {
                e = random_big.NextBigInteger(random.Next(2, get_bit(N) - 1));
                e += 2;
                if (ucln(e, n) == 1 && e < N) break;
            };
            d = inverse_number(e, n);
            mid_e = inverse_number(d, n);
        }

        bool is_prime(BigInteger p)
        {
            if (p == 3 || p == 5 || p == 7 || p == 11 || p == 13 || p == 17) return true;
            BigInteger a, k = 0, q = 0;

            bool kt = false;
            transform(p, ref k, ref q);
            for (int i = 0; i < 10; i++)
            {
                a = i + 3;
                if (miller_rabin(p, k, q, a) == true) kt = true;
                if (kt == false) return false;
            }
            return true;
        }

        BigInteger random_odd(int length)
        {
            BigInteger a = 10;

            do
                a = random_big.NextBigInteger(length);
            while (a % 2 == 0);
            return a;
        }

        int get_bit(BigInteger n)
        {
            int dem = 0;

            while (n > 0)
            {
                n = n / 2;
                dem++;
            }
            return dem;
        }
        public string tranform_binary(BigInteger n)
        {
            int i;
            string st = "";
            BigInteger[] a = new BigInteger[3000];

            for (i = 0; n > 0; i++)
            {
                a[i] = n % 2;
                n = n / 2;
            }

            for (i = i - 1; i >= 0; i--)
                st += a[i];
            return st;
        }

        public string tranform_decimal(string st)
        {
            BigInteger n = BigInteger.Parse(st);
            BigInteger kq = 0;
            BigInteger luy_thua = 1;
            while (n != 0)
            {
                BigInteger r = n % 10;
                n = n / 10;
                if (r == 1)
                    kq += luy_thua;
                luy_thua = 2 * luy_thua;
            }
            return "" + kq;
        }

        void transform(BigInteger p, ref BigInteger k, ref BigInteger q)
        {
            p--;
            while (p % 2 == 0)
            {
                k++;
                p = p / 2;
            }
            q = p;
        }

        bool miller_rabin(BigInteger p, BigInteger k, BigInteger q, BigInteger a)
        {

            BigInteger x = fast_exp(a, q, p);

            if (x == 1) return true;
            for (int i = 0; i < k; i++)
            {
                if (x == p - 1) return true;
                x = x * x % p;
            }
            return false;
        }

        BigInteger fast_exp(BigInteger m, BigInteger e, BigInteger p)
        {
            BigInteger kq = 1;
            int i, n = 0;
            BigInteger[] b = new BigInteger[809060];

            for (i = 1; e > 0; i++)
            {
                b[i] = e % 2;
                e = e / 2;
            }
            n = i;

            for (i = n; i >= 1; i--)
            {
                kq = kq * kq % p;
                if (b[i] == 1)
                    kq = kq * m % p;
            }
            return kq;
        }

        BigInteger inverse_number(BigInteger a, BigInteger m)
        {
            BigInteger y = 0, y0 = 0, y1 = 1, r = 1, q = 1, m1 = m;

            while (a > 0)
            {
                r = m % a;
                if (r == 0) break;
                q = m / a;
                y = y0 - y1 * q;
                y0 = y1;
                y1 = y;
                m = a;
                a = r;
            }
            if (a > 1)
                return -1;
            else
            {
                if (y < 0) y = m1 + y;
                return y;
            }
        }
        BigInteger ucln(BigInteger a, BigInteger b)
        {
            BigInteger temp;

            while (b != 0)
            {
                temp = a % b;
                a = b;
                b = temp;
            }
            return a;
        }
    }
}

QLSV_BlockChain/Areas/KiemDinh/Views/Shared/_layoutKiemDinh.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Dashboard - SB Admin</title>
    <link href="~/Content/layoutAdmin/css/styles.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" crossorigin="anonymous"></script>
</head>
@{
    var userAdmin = Session["userAdmin"] as QLSV_BlockChain.Models.NguoiDung;

}
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark badge-success">
        <a class="navbar-brand" href="#"><img src="~/Content/images/logo.png" width="210" height="50" /></a>
        <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#">
            <i class="fas fa-bars"></i>
        </button><!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Từ khóa..." aria-label="Search" aria-describedby="basic-addon2" />
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
                </div>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="#">Cài đặt</a><a class="dropdown-item" href="#">Nhật kí</a>
                    <div class="dropdown-divider"></div>
                    <a class=" dropdown-item" href="@Url.Action("Dangxuat", "KiemDinhDiem")"> Đăng xuất</a>

                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        @{
                            if (userAdmin != null)
                            {
                                <div class="sb-sidenav-menu-heading" style="color:red">Xin chào: @userAdmin.TaiKhoan </div>

                            }
                        }
                        <div class="sb-sidenav-menu-heading"> <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>Quản lý chức năng</div>
                        <a class="nav-link" href="@Url.Action("Index", "KiemDinhDiem")"> <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>Tất cả bảng điểm</a>
                        <a class="nav-link" href="@Url.Action("Index", "ChuKyRSA")"> <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>Tạo chữ ký RSA</a>

                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Đồ án chuyên ngành</div>
                    Nhóm 10
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted"> CNTT- HUTECH &copy; 2022</div>
                        <div>
                            <a href="#"> Xem thêm</a>
                            &middot;
                            <a href="#">BlockChain &amp; ATTT</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/Content/layoutAdmin/js/scripts.js"></script>
</body>
</html>